import type { Tender } from "../domain/tender.js";
import { TenderSchema } from "../domain/tender.js";
import { dedupeTenders, fetchWithRetry } from "./source-utils.js";

export type NicGePSource = { key: string; name: string; url: string; location: string };
export const NIC_GEP_SOURCES: NicGePSource[] = [
  { key: "maharashtra", name: "Maharashtra eProcurement", url: "https://mahatenders.gov.in/nicgep/app", location: "Maharashtra" },
  { key: "madhya-pradesh", name: "Madhya Pradesh eProcurement", url: "https://mpeproc.gov.in/", location: "Madhya Pradesh" },
  { key: "west-bengal", name: "West Bengal eTender", url: "https://etender.wb.nic.in/nicgep/app", location: "West Bengal" },
  { key: "kerala", name: "Kerala eTender", url: "https://etenders.kerala.gov.in/nicgep/app", location: "Kerala" },
  { key: "uttarakhand", name: "Uttarakhand eTender", url: "https://uktenders.gov.in/nicgep/app", location: "Uttarakhand" },
  { key: "rajasthan", name: "Rajasthan eProcurement", url: "https://www.eproc.rajasthan.gov.in/nicgep/app", location: "Rajasthan" },
  { key: "tamil-nadu", name: "Tamil Nadu eProcurement", url: "https://tntenders.gov.in/nicgep/app", location: "Tamil Nadu" },
];
function clean(value: string): string { return value.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]*>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g," ").trim(); }
function parseDate(value: string): string | undefined { const m=value.match(/(\d{1,2})[-/](\d{1,2})[-/](\d{4})\s+(\d{1,2}):(\d{2})\s*(AM|PM)?/i); if(!m)return undefined; const[,day,month,year,hourRaw,minute,ampm]=m; let hour=Number(hourRaw); if(ampm?.toUpperCase()==="PM"&&hour<12)hour+=12;if(ampm?.toUpperCase()==="AM"&&hour===12)hour=0;const date=new Date(Date.UTC(Number(year),Number(month)-1,Number(day),hour,Number(minute)));return Number.isNaN(date.getTime())?undefined:date.toISOString(); }
function absoluteUrl(base:string,href:string):string{try{return new URL(href,base).toString();}catch{return base;}}
function parseSource(source:NicGePSource,html:string):Tender[]{const tenders:Tender[]=[];for(const row of html.match(/<tr[^>]*>[\s\S]*?<\/tr>/gi)??[]){const cells=[...row.matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(m=>clean(m[1]));if(cells.length<2||cells.some(c=>/tender title|reference no|closing date/i.test(c)))continue;const dates=[...row.matchAll(/\d{1,2}[-/]\d{1,2}[-/]\d{4}(?:\s+\d{1,2}:\d{2}\s*(?:AM|PM)?)?/gi)].map(m=>m[0]);const closingAt=parseDate(dates[0]??"");if(!closingAt)continue;const refIndex=cells.findIndex(c=>/[A-Z0-9][A-Z0-9./()_-]{4,}/i.test(c)&&c.length<180);const referenceNumber=refIndex>=0?cells[refIndex]:undefined;const title=cells.find((c,i)=>i!==refIndex&&c.length>=12&&!/^\d{1,2}[-/]\d{1,2}[-/]\d{4}/.test(c));if(!referenceNumber||!title)continue;const links=[...row.matchAll(/href=["']([^"']+)["']/gi)].map(m=>absoluteUrl(source.url,m[1]));const sourceUrl=links.find(url=>/tender|nicgep|nit|details/i.test(url))??source.url;try{tenders.push(TenderSchema.parse({id:`nicgep:${source.key}:${referenceNumber}`,referenceNumber:referenceNumber.slice(0,300),title:title.slice(0,500),location:source.location,closingAt,source:source.name,sourceUrl,keywords:title.toLowerCase().split(/[^a-z0-9]+/i).filter(word=>word.length>2).slice(0,40),description:title.slice(0,2000),raw:{portal:source.key,listingUrl:source.url,fetchedAt:new Date().toISOString()}}));}catch{}}
return dedupeTenders(tenders);}
export async function fetchNicGePTenders(source:NicGePSource):Promise<Tender[]>{const response=await fetchWithRetry(source.url,{headers:{accept:"text/html,application/xhtml+xml","user-agent":"TenderIntelligenceSaaS/1.1 (+public-tender-indexer)"},timeoutMs:30_000,retries:2});if(!response.ok)throw new Error(`${source.name} returned HTTP ${response.status}`);const tenders=parseSource(source,await response.text());if(!tenders.length)throw new Error(`${source.name} returned no parseable public tenders; portal markup may have changed.`);return tenders;}
export async function fetchAllNicGePTenders():Promise<{tenders:Tender[];errors:string[];counts:Record<string,number>}>{const results=await Promise.allSettled(NIC_GEP_SOURCES.map(fetchNicGePTenders));const tenders=dedupeTenders(results.flatMap(r=>r.status==="fulfilled"?r.value:[]));const errors=results.map((r,i)=>r.status==="rejected"?`${NIC_GEP_SOURCES[i].name}: ${String(r.reason)}`:undefined).filter(Boolean) as string[];const counts:Record<string,number>={};for(const tender of tenders)counts[tender.source]=(counts[tender.source]??0)+1;return{tenders,errors,counts};}
